#!/bin/bash
install_path=`pwd`
chmod +x "$install_path/myvlcplayer"
chmod +x "$install_path/My VLCplayer.desktop"
sudo cp -rf "$install_path/myvlcplayer" /usr/bin/
sudo cp -rf "$install_path/My VLCplayer.desktop" /usr/share/applications/
